# Generated by Django 5.0.6 on 2024-07-06 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_sys', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
