# Generated by Django 5.0.6 on 2024-07-06 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_media', '0002_channel_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='channelpost',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='userpost',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='channel',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='channel/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='channelpost',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='post/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='userpost',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='post/%Y/%m/%d/'),
        ),
    ]
